[base]
policy_name = "CleanRLPolicy"

# From https://wandb.ai/kywch/carbs/runs/6lwpqagr
[train]
seed = 1
torch_deterministic = true
cpu_offload = false
device = "cuda"
learning_rate = 0.0005777595353493435
anneal_lr = false
gamma = 0.9838324555417536
gae_lambda = 0.7782845948538163
update_epochs = 8
norm_adv = true
clip_coef = 0.28654484839824146
clip_vloss = true
vf_coef = 1.2300177812576294
vf_clip_coef = 0.9663969573561514
max_grad_norm = 0.5
ent_coef = 0.000374745090906141
# target_kl = None  # Assign a value when needed.

num_envs = 32
num_workers = 16
env_batch_size = 16
zero_copy = false
data_dir = "experiments"
checkpoint_interval = 125
batch_size = 16384
minibatch_size = 2048
bptt_horizon = 16

total_timesteps = 10_000_000

# Check if the results are the same before compiling
compile = false
compile_mode = "reduce-overhead"

# Extra steps to evaluate the agent after training
eval_timesteps = 1_000_000
